DROP DATABASE IF EXISTS portfolio;
CREATE DATABASE portfolio;

DROP DATABASE IF EXISTS trade_history_db;
CREATE DATABASE trade_history_db;

DROP DATABASE IF EXISTS userDB;
CREATE DATABASE userDB;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
